// This file was autogenerated by closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../source/server2js.export.js', ['ssd.server'], ['ssd.server2js', 'ssd.Server2js']);
goog.addDependency('../source/server2.js', ['ssd.Server2js', 'ssd.server2js'], []);
